{
 "title": "Cloudflare Analytics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": "{\"find\": \"terms\", \"field\": \"zoneName.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Unique Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "uniques", "id": "1", "type": "sum" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    },
    {
     "alias": "Uniques",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "uniques", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    },
    {
     "alias": "Page Views",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "pageViews", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests Error-Success Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "sum" }
     ],
     "query": "dataType: \"responseStatus\" AND zoneName:$zone AND dataKey:[500 TO 599]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "sum" }
     ],
     "query": "dataType: \"responseStatus\" AND zoneName:$zone AND dataKey:[200 TO 399]",
     "timeField": "@timestamp"
    },
    {
     "alias": "Client Issues",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "sum" }
     ],
     "query": "dataType: \"responseStatus\" AND zoneName:$zone AND dataKey:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests by ResponseStatus",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dataKey.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "sum" }
     ],
     "query": "dataType: \"responseStatus\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests for ContentTypes",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dataKey.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"contentType\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests by Country",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 17 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "dataType: \"country\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cached Request Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "cached requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cachedRequests", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    },
    {
     "alias": "total requests",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "requests", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"base\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Browser Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dataKey.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "pageViews", "id": "1", "type": "max" }
     ],
     "query": "dataType: \"browser\" AND zoneName:$zone",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}